### ISSUE TITLE
web_demo对话报错

### ISSUE THREAD

**Issue by KonngExplorer** [OpenBMB/BMTools#44]
Traceback (most recent call last):
  File "D:\miniconda3\envs\bmtool\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\miniconda3\envs\bmtool\lib\site-packages\gradio\blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "D:\miniconda3\envs\bmtool\lib\site-packages\gradio\blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\miniconda3\envs\bmtool\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "D:\miniconda3\envs\bmtool\lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\miniconda3\envs\bmtool\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\miniconda3\envs\bmtool\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\miniconda3\envs\bmtool\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\miniconda3\envs\bmtool\lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "E:\workspace_shgl\BMTools-main\web_demo.py", line 63, in answer_by_tools
    for inter in agent_executor(question):
  File "E:\workspace_shgl\BMTools-main\bmtools\agent\executor.py", line 99, in __call__
    self.callback_manager.on_chain_start(
AttributeError: 'Executor' object has no attribute 'callback_manager'

**Comment by congxin95** [comment]
It seems that the version of langchain is incorrect causing the function cannot found. Could provide more detailed error information like library version, tools you used, questions you asked.

**Comment by for1314ai** [comment]
Traceback (most recent call last):
  File "/appletree/shiwei/BMTools/web_demo.py", line 47, in <module>
    valid_tools_info = load_valid_tools(tools_mappings)
  File "/appletree/shiwei/BMTools/bmtools/agent/tools_controller.py", line 22, in load_valid_tools
    response = requests.get(get_url)
  File "/appletree/miniconda3/envs/sw_tool/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/appletree/miniconda3/envs/sw_tool/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/appletree/miniconda3/envs/sw_tool/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/appletree/miniconda3/envs/sw_tool/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/appletree/miniconda3/envs/sw_tool/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8079): Max retries exceeded with url: /tools/weather/.well-known/ai-plugin.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffa95955f70>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by michaelxu1107** [comment]
这个问题后面有解决么，我这边使用的langchain版本是0.0.193，使用的是单个tool问答，也碰到了
类似File "E:\workspace_shgl\BMTools-main\bmtools\agent\executor.py", line 99, in call
self.callback_manager.on_chain_start(
AttributeError: 'Executor' object has no attribute 'callback_manager'的问题

**Comment by michaelxu1107** [comment]
'''
Traceback (most recent call last):
  File "/root/venv/lib/python3.10/site-packages/gradio/routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "/root/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1059, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/venv/lib/python3.10/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/root/venv/lib/python3.10/site-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/venv/lib/python3.10/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "./web_demo.py", line 86, in answer_by_tools
    for inter in agent_executor(question):
  File "/root/BMTools-main/./bmtools/agent/executor.py", line 99, in __call__
    self.callback_manager.on_chain_start(
AttributeError: 'NoneType' object has no attribute 'on_chain_start'
'''
