### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by zhongyy** [OpenBMB/BMTools#52]
Thank you for the excellent work. I am trying the test.py.

```
from bmtools.agent.singletool import load_single_tools, STQuestionAnswerer

# Langchain
tool_name, tool_url = 'weather',  "http://127.0.0.1:8079/tools/weather/"
tool_name, tool_config = load_single_tools(tool_name, tool_url)
print(tool_name, tool_config)
stqa =  STQuestionAnswerer()

agent = stqa.load_tools(tool_name, tool_config, prompt_type="react-with-tool-description")
agent("write a weather report for SF today")
```
However, the connection error bothers me a lot. 
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8079): Max retries exceeded with url: /tools/weather/.well-known/ai-plugin.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96cfbcd1b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
``` 
I have checked the previous issues and still have no idea what I should do to solve it. Would you like to give some suggestions?

**Comment by yDing121** [comment]
Not on the team but have you run the tool server `./host_local_tools.py`, and made sure that the tool that you are trying to test is enabled in `./host_local_tools.py`? There should be a long list of `load_<toolname>_tool()` commands at the bottom of `./host_local_tools.py` - make sure the tool you are trying to access is not commented out e.g. for the weather tool, make sure python actually runs `load_weather_tool()`.

**Comment by zhongyy** [comment]
> Not on the team but have you run the tool server `./host_local_tools.py`, and made sure that the tool that you are trying to test is enabled in `./host_local_tools.py`? There should be a long list of `load_<toolname>_tool()` commands at the bottom of `./host_local_tools.py` - make sure the tool you are trying to access is not commented out e.g. for the weather tool, make sure python actually runs `load_weather_tool()`.

Thank you！I have run `./host_local_tools.py` before. `load_weather_tool()` has been loaded. However, I am confused about how to ` Then set the url of the plugin to http://127.0.0.1:8079/tools/{tool_name}/ (Remember the tailing /)`.

**Comment by zhongyy** [comment]
I have set `server.serve(host="127.0.0.1", port=8079)` in `host_local_tools.py`. But there is still the same error.

```
Traceback (most recent call last):
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f08661f0f40>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8079): Max retries exceeded with url: /tools/weather/.well-known/ai-plugin.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f08661f0f40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhongyaoyao/projects/BMTools/test.py", line 5, in <module>
    tool_name, tool_config = load_single_tools(tool_name, tool_url)
  File "/home/zhongyaoyao/projects/BMTools/bmtools/agent/singletool.py", line 56, in load_single_tools
    response = requests.get(get_url)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/zhongyaoyao/anaconda3/envs/tool/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8079): Max retries exceeded with url: /tools/weather/.well-known/ai-plugin.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f08661f0f40>: Failed to establish a new connection: [Errno 111] Connection refused'))


```
